services:
  addon-manager:
    image: reddravenn/stremio-addon-manager:latest
    container_name: addon-manager
    restart: unless-stopped
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.addon-manager.rule=Host(`${ADDON_MANAGER_HOSTNAME?}`)"
      - "traefik.http.routers.addon-manager.entrypoints=websecure"
      - "traefik.http.routers.addon-manager.tls.certresolver=letsencrypt"
      - "traefik.http.routers.addon-manager.middlewares=authelia@docker"
      - homepage.name=Stremio Addon Manager
      - homepage.group=Stremio
      - homepage.description=Stremio add-on for torrents.
      - homepage.href=https://${ADDON_MANAGER_HOSTNAME?}
      - homepage.icon=https://addon-manager.somesuchnonsense.cc/logo.png
    profiles:
      - addon-manager
      - stremio
      - all
