include:
  - apps/addon-manager/compose.yaml
  - apps/aiolists/compose.yaml
  - apps/aiometadata/compose.yaml
  - apps/aiostreams/compose.yaml
  - apps/aiostremio/compose.yaml
  - apps/arcane/compose.yaml
  - apps/authelia/compose.yaml
#  - apps/autosync/compose.yaml
#  - apps/bazarr/compose.yaml
#  - apps/beszel/compose.yaml
#  - apps/borgmatic/compose.yaml
  - apps/byparr/compose.yaml
  - apps/cloudflare-ddns/compose.yaml
  - apps/comet/compose.yaml
#  - apps/crowdsec/compose.yaml
  - apps/dash/compose.yaml
  - apps/decypharr/compose.yaml
#  - apps/discord-tickets/compose.yaml
#  - apps/dockge/compose.yaml
  - apps/dozzle/compose.yaml
  #- apps/easynews-plus/compose.yaml
#  - apps/easynews-plus-plus/compose.yaml
  - apps/homarr/compose.yaml
  - apps/honey/compose.yaml
#  - apps/huntarr/compose.yaml
#  - apps/iptvboss/compose.yaml
#  - apps/it-tools/compose.yaml
  - apps/jackett/compose.yaml
#  - apps/jackettio/compose.yaml
  - apps/jellyfin/compose.yaml
#  - apps/jellyseer/compose.yaml
#  - apps/kometa/compose.yaml
#  - apps/mealie/compose.yaml
#  - apps/mediaflow-proxy/compose.yaml
  - apps/mediafusion/compose.yaml
#  - apps/nitter/compose.yaml
#  - apps/nzbhydra2/compose.yaml
#  - apps/overseerr/compose.yaml
#  - apps/plex/compose.yaml
#  - apps/plex-trakt-sync/compose.yaml
#  - apps/plexio/compose.yaml
  - apps/portainer/compose.yaml
  - apps/prowlarr/compose.yaml
  - apps/radarr/compose.yaml
  - apps/redlib/compose.yaml
#  - apps/recyclarr/compose.yaml
#  - apps/seanime/compose.yaml
#  - apps/searxng/compose.yaml
  - apps/sonarr/compose.yaml
  - apps/stremio-ai-companion/compose.yaml
  - apps/stremio-ai-search/compose.yaml
#  - apps/stremio-letterboxd/compose.yaml
  #- apps/stremio-server/compose.yaml
  - apps/stremio-trakt-addon/compose.yaml
  - apps/stremthru/compose.yaml
  - apps/syncribullet/compose.yaml
  #- apps/tandoor/compose.yaml
  - apps/torbox-manager/compose.yaml
  - apps/torbox-media-center/compose.yaml
  - apps/traefik/compose.yaml
  - apps/tweakio/compose.yaml
 # - apps/uptime-kuma/compose.yaml
 # - apps/vaultwarden/compose.yaml
  - apps/warp/compose.yaml
  - apps/watchtower/compose.yaml
  - apps/yamtrack/compose.yaml
  - apps/zilean/compose.yaml
#  - apps/zipline/compose.yaml
  # Uncomment if you are using zurg and comment out decypharr
  # There is also a way to use both together, but it requires 2 rclone instances
  # To use both, update Zurg's rclone service name and its container name to rclone_zurg
  # You will also need to change Zurg's rclone's `- apps//mnt/remote/realdebrid:/data:rshared` to `- apps//mnt/remote/zurg:/data:rshared`
  # - apps/zurg/compose.yaml
  # same as above for using debridav, Uncomment debridav and comment out decypharr and zurg
  # - apps/debridav/compose.yaml
  - apps/obsidian-livesync/compose.yaml
  - apps/technitium/compose.yaml
networks:
  default:
    name: ${DOCKER_NETWORK:-aio_default}
    external: ${DOCKER_NETWORK_EXTERNAL:-false}