services:
  aiolists:
    build:
      context: https://github.com/SebastianMorel/AIOLists.git
      dockerfile: Dockerfile
    container_name: aiolists
    restart: unless-stopped
    expose:
      - 7000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiolists.rule=Host(`${AIOLISTS_HOSTNAME?}`)"
      - "traefik.http.routers.aiolists.entrypoints=websecure"
      - "traefik.http.routers.aiolists.tls.certresolver=letsencrypt"
      - "traefik.http.routers.aiolists.middlewares=authelia@docker"
      - homepage.name=AIOLists
      - homepage.group=Stremio
      - homepage.descrption=All-In-One lists add-on for Stremio.
      - homepage.href=https://${AIOLISTS_HOSTNAME?}
      - homepage.icon=stremio
    profiles:
      - aiolists
      - stremio
      - all