users:
    ssnadmin:
        password: $argon2id$v=19$m=65536,t=3,p=4$sOssOiwM7/80diMnSG6Bow$pH3nxCPtR8RS3Ryykhy+OnefwjEMXylSvRc4oK3iG4A
        displayname: ssnadmin
        email: onlyelliot@gmail.com
        groups:
            - admins
            - dev
        given_name: ""
        middle_name: ""
        family_name: ""
        nickname: ""
        gender: ""
        birthdate: ""
        website: ""
        profile: ""
        picture: ""
        zoneinfo: ""
        locale: ""
        phone_number: ""
        phone_extension: ""
        disabled: false
        address: null
        extra: {}
