services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync
    environment:
      - COUCHDB_USER=elliotobsidian
      - COUCHDB_PASSWORD=supersecretpassword
    user: $PUID:$PGID
    volumes:
      - ${DOCKER_DATA_DIR}/obsidian-livesync:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian-livesync.rule=Host(`${OBSIDIAN_LIVESYNC_HOSTNAME?}`)"
      - "traefik.http.routers.obsidian-livesync.entrypoints=websecure"
      - "traefik.http.routers.obsidian-livesync.tls.certresolver=letsencrypt"
      - "traefik.http.routers.obsidian-livesync.middlewares=obsidian-cors@docker"
      - "traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984"
      - "traefik.http.middlewares.obsidian-cors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE,OPTIONS"
      - "traefik.http.middlewares.obsidian-cors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidian-cors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
      - "traefik.http.middlewares.obsidian-cors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidian-cors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidian-cors.headers.accessControlAllowCredentials=true"
    profiles:
      - all
      - obsidian-livesync